load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

ENNBO_SRCS = glob(
    ["src/**/*.rs"],
    exclude = ["src/ennbo_build.rs"],
)

ENNBO_DEPS = all_crate_deps(normal = True) + [
    "//rust/crates/bpann",
]

cc_library(
    name = "faiss_bridge",
    srcs = ["src/faiss_bridge.cpp"],
    copts = select({
        "@platforms//os:windows": ["/std:c++17"],
        "//conditions:default": ["-std=c++17"],
    }),
    deps = ["@faiss_src//:faiss"],
)

rust_library(
    name = "ennbo_cpu",
    srcs = ENNBO_SRCS,
    aliases = aliases(),
    crate_name = "ennbo",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    link_deps = [":faiss_bridge"],
    deps = ENNBO_DEPS,
)

rust_library(
    name = "ennbo_metal",
    srcs = ENNBO_SRCS,
    aliases = aliases(),
    compile_data = glob(["src/**/*.metal"]),
    crate_features = ["metal"],
    crate_name = "ennbo",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    link_deps = [":faiss_bridge"],
    deps = ENNBO_DEPS + [
        "@accelerator_crates//:metal",
    ],
    target_compatible_with = ["@platforms//os:macos"],
)

rust_library(
    name = "ennbo_opencl",
    srcs = ENNBO_SRCS,
    aliases = aliases(),
    compile_data = glob(["src/**/*.cl"]),
    crate_features = ["opencl"],
    crate_name = "ennbo",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    link_deps = [":faiss_bridge"],
    deps = ENNBO_DEPS + [
        "@accelerator_crates//:opencl3",
    ],
)

alias(
    name = "ennbo",
    actual = ":ennbo_cpu",
)

alias(
    name = "ennbo_accelerators",
    actual = select({
        "@platforms//os:linux": ":ennbo_opencl",
        "@platforms//os:macos": ":ennbo_metal",
        "@platforms//os:windows": ":ennbo_opencl",
        "//conditions:default": ":ennbo_cpu",
    }),
)

rust_test(
    name = "ennbo_test",
    crate = ":ennbo_cpu",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True, proc_macro_dev = True),
)

rust_test(
    name = "trial_search_metal_test",
    srcs = ["tests/trial_search.rs"],
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    crate_features = ["metal"],
    crate_name = "trial_search_metal_test",
    crate_root = "tests/trial_search.rs",
    edition = crate_edition(),
    deps = all_crate_deps(normal_dev = True, proc_macro_dev = True) + [
        ":ennbo_metal",
        "@crates//:ndarray",
    ],
    target_compatible_with = ["@platforms//os:macos"],
)
