genrule(
    name = "dense-static",
    srcs = [
        "src/dense.zig",
        "src/root.zig",
    ],
    out = "ennx_dense.lib",
    cmd = "zig build-lib $SRCDIR/src/root.zig -OReleaseFast -fPIC -fno-emit-h -femit-bin=$OUT",
)

prebuilt_cxx_library(
    name = "dense",
    force_static = True,
    preferred_linkage = "static",
    static_lib = ":dense-static",
    static_pic_lib = ":dense-static",
    visibility = ["PUBLIC"],
)
