[experiment]
exp_dir = "results/validate_turbo"
env_tag = "tlunar:fn"
policy_tag = "turbo-lunar"
opt_name = "turbo-m"
num_arms = 50
num_rounds = 30
num_denoise = 50
num_reps = 10

[trust_region]
kind = "multi_tr"
num_regions = 4
sharing_policy = "shared"
succ_tolerance = 3
fail_tolerance = 5
length_init = 0.8
length_min = 0.5
length_max = 1.6
